### PR TITLE
[OPALSUP-280] Order marketplace alphabetically

### PR DESCRIPTION
**Pull request by jlove-nz**

### CODE REVIEW

**Comment by jlove-nz** [comment]
@alexmaestrano  You're right v4.0 introduces some changes (Initially I had assumed we were using v4 as v3 is 3 years old). The entire codebase is going to have to be reviewed for v4.0 compatibility.

**Comment by jlove-nz** [comment]
@adamaziz15 I have rebased this against 2.0 head. However I noticed that sorting case sensitively wasn't good.  I've fixed this.

Sorry, but can you please re-review.

**Comment by ouranos** [comment]
Shouldn't this be done in the `mno-enterprise`?
We already [sort by rank in the MarketplaceController](https://github.com/maestrano/mno-enterprise/blob/4.0/api/lib/mno_enterprise/concerns/controllers/jpi/v1/marketplace_controller.rb#L85)
Might as well do it there too and that gives us caching as well

**Comment by jlove-nz** [comment]
@ouranos Fair point - I understand that the marketplace ordering is a strong opinion so it makes sense to do it in the middleware layer. For some reason I though this was handled in the core Hub.

Note that the local products listing will still be sorted client side as it uses the products list, not the apps list.

**Comment by ouranos** [comment]
Agree with the middleware layer comment.
Let's order the local products in `mno-enterprise` too (we can pass the ordering to the JSON API so MnoHub returns an already sorted array)

**Comment by jlove-nz** [comment]
@ouranos The hub sorting doesn't sort case insensitively. Is this something you'd look to fix in Hub?

**Comment by ouranos** [comment]
@jlove-nz I think it does?

I have the following reseller products:
image

Then if I do `GET {{mnohub}}/api/mnoe/v2/products?fields[products]=name&sort=name&filter[local]=true`

I get:
```json
{
    "data": [
        {
            "id": "21c2f27a-2286-4ab0-b73c-d176e41bb82b",
            "type": "products",
            "links": {
                "self": "https://api-hub.uat.opal.maestrano.io/api/mnoe/v2/products/21c2f27a-2286-4ab0-b73c-d176e41bb82b"
            },
            "attributes": {
                "name": "AA"
            }
        },
        {
            "id": "71167d78-f21a-476e-924b-8a7dc62d2326",
            "type": "products",
            "links": {
                "self": "https://api-hub.uat.opal.maestrano.io/api/mnoe/v2/products/71167d78-f21a-476e-924b-8a7dc62d2326"
            },
            "attributes": {
                "name": "aaa"
            }
        },
        {
            "id": "047eff8a-bbda-4366-9dff-6a8535b83d98",
            "type": "products",
            "links": {
                "self": "https://api-hub.uat.opal.maestrano.io/api/mnoe/v2/products/047eff8a-bbda-4366-9dff-6a8535b83d98"
            },
            "attributes": {
                "name": "ab"
            }
        },
        {
            "id": "522e062d-d39f-4c0a-8aae-6a674d79904a",
            "type": "products",
            "links": {
                "self": "https://api-hub.uat.opal.maestrano.io/api/mnoe/v2/products/522e062d-d39f-4c0a-8aae-6a674d79904a"
            },
            "attributes": {
                "name": "AC"
            }
        },
        {
            "id": "8e6cfb0f-ac23-4b1a-a74a-9d40bb0c6941",
            "type": "products",
            "links": {
                "self": "https://api-hub.uat.opal.maestrano.io/api/mnoe/v2/products/8e6cfb0f-ac23-4b1a-a74a-9d40bb0c6941"
            },
            "attributes": {
                "name": "Test NZ Product"
            }
        }
    ],
}
```

**Comment by jlove-nz** [comment]
@ouranos You're quite right. My testing was invalid.  I'm going to close this PR and open a new one for server side sorting.

**Pull request closed without merging**
